### ISSUE TITLE
Use of Digital Trigger for Analog Acquisition

### ISSUE THREAD

**Issue by bhclowers** [mariusgreuel/dwfpy#3]
Is it possible to use the digital input trigger to start the acquisition of the analog channels? I know this is possible via Waveforms, but I would like to acquire data in a more defined fashion. The [analog_in_record.py](https://github.com/mariusgreuel/dwfpy/blob/754930c5a816f2f3368006baec7617ab66c79edf/examples/analog_in_record.py) example uses either channel 0 or 1 for the trigger:

```python
  scope[0].setup(range=5)
  scope.setup_edge_trigger(
      mode='normal', channel=0, slope='rising', level=0, hysteresis=0.01, position=-0.25
  )
  recorder = scope.record(sample_rate=100e3, length=2, configure=True, start=True)
 ```
Is there a way to change the trigger channel source to ```logic.setup_trigger(source='detector-digital-in') ``` or an equivalent digital pin?

**Comment by mariusgreuel** [comment]
Yes, you can access all trigger properties directly via the [AnalogInputTrigger](https://dwfpy.readthedocs.io/en/latest/_autosummary/dwfpy.analog_input.AnalogInputTrigger.html) class.

```python
scope.trigger.source = TriggerSource.DIGITAL_IN
scope.trigger.condition = TriggerSlope.RISE
```
