### ISSUE TITLE
Data recording on specific channels

### ISSUE THREAD

**Issue by abhinavG37** [mariusgreuel/dwfpy#4]
Hi @mariusgreuel! Could you please confirm the functionality of data recording on dwfpy? 
I would like to simultaneously record information for 7 digital input channels.  
From what I can understand, the following line of code:
`logic.record(sample_rate=10e3, sample_format=32,sample_count=SAMPLE_COUNT // 2,prefill=SAMPLE_COUNT // 2, start=True)` records only a single np.ndarray with the number of specified samples. How does the API decide which channel to record, and how do I selectively record a specific digital-input.

Your help would be highly appreciated.

**Comment by mariusgreuel** [comment]
> How does the API decide which channel to record

AFAIK, you cannot specify the channels. You can only specify how many channels you want (as in Waveforms), and the channels are DIN0...DINn. So you either record all of them, or you need to rewire your setup.

**Comment by abhinavG37** [comment]
I'd go with recording all the channels. If you'd have some sample code to help me get started, I'd highly appreciate it. I have only been able to get single channel data out of it (single dim ndarray when logic.record() is called). Thank you so much.

**Comment by mariusgreuel** [comment]
The returned vector is always one-dimensional. If you record 32 channels, it returns a `c_uint32` vector, where the individual channels are encoded in the respective bits of the `c_uint32`.

Check out <https://github.com/mariusgreuel/dwfpy/blob/main/examples/digital_in_record.py>

**Comment by abhinavG37** [comment]
Thank you, that worked perfectly!

**Comment by bojanpotocnik** [comment]
> AFAIK, you cannot specify the channels.
> So you either record all of them, or you need to rewire your setup.
> I'd go with recording all the channels.

As I was wondering the same today, I will leave this link here for information: https://forum.digilent.com/topic/4425-waveforms-sdk-in-python-choosing-digitalin-channels/
> There is no need to enable the digital inputs, these are always available to read.
The DigitalIO data and DigitalIn acquisition sample bits represent the digital channels. The least significant bit (0) being DIO (channel) 0, bit 1 = DIO 1,...

In a nutshell, the hardware always samples all DIO channels, and the `sample_format` argument specifies how many channels the library retrieves from the instrument (see [WaveForms SDK Reference Manual](https://digilent.com/reference/software/waveforms/waveforms-sdk/reference-manual#control2), `FDwfDigitalInSampleFormatSet` and `FDwfDigitalInStatusData2`).

I do this to optimize USB bandwidth:
```python
sample_format=8 * math.ceil(num_channels / 8),  # Retrieve 8, 16, or 32 bits (DIO channels)
```
and the following function on `data_samples`
```python
def extract_channel(samples: np.array, channel: int) -> np.array:
    """
    Extract a single channel as a boolean array from the array of samples

    The shape of the data_samples array is (sample_count,), because each
    bit of the value represents the DI channel state  at a given time
    (the least significant bit (0) being DIO 0, bit 1 = DIO 1, etc.).
    This is why the dtype is uint8, uint16, or uint32 for 8, 16, or 32
    captured channels respectively (specified with sample_format).
    """
    return ((samples >> channel) & 1).astype(bool)
```
